// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/sumpb/sum.proto

package sumpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sum struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sum) Reset()         { *m = Sum{} }
func (m *Sum) String() string { return proto.CompactTextString(m) }
func (*Sum) ProtoMessage()    {}
func (*Sum) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{0}
}

func (m *Sum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sum.Unmarshal(m, b)
}
func (m *Sum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sum.Marshal(b, m, deterministic)
}
func (m *Sum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sum.Merge(m, src)
}
func (m *Sum) XXX_Size() int {
	return xxx_messageInfo_Sum.Size(m)
}
func (m *Sum) XXX_DiscardUnknown() {
	xxx_messageInfo_Sum.DiscardUnknown(m)
}

var xxx_messageInfo_Sum proto.InternalMessageInfo

func (m *Sum) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Sum) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type DoSumRequest struct {
	Sum                  *Sum     `protobuf:"bytes,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSumRequest) Reset()         { *m = DoSumRequest{} }
func (m *DoSumRequest) String() string { return proto.CompactTextString(m) }
func (*DoSumRequest) ProtoMessage()    {}
func (*DoSumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{1}
}

func (m *DoSumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSumRequest.Unmarshal(m, b)
}
func (m *DoSumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSumRequest.Marshal(b, m, deterministic)
}
func (m *DoSumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSumRequest.Merge(m, src)
}
func (m *DoSumRequest) XXX_Size() int {
	return xxx_messageInfo_DoSumRequest.Size(m)
}
func (m *DoSumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoSumRequest proto.InternalMessageInfo

func (m *DoSumRequest) GetSum() *Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

type DoSumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoSumResponse) Reset()         { *m = DoSumResponse{} }
func (m *DoSumResponse) String() string { return proto.CompactTextString(m) }
func (*DoSumResponse) ProtoMessage()    {}
func (*DoSumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{2}
}

func (m *DoSumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoSumResponse.Unmarshal(m, b)
}
func (m *DoSumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoSumResponse.Marshal(b, m, deterministic)
}
func (m *DoSumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoSumResponse.Merge(m, src)
}
func (m *DoSumResponse) XXX_Size() int {
	return xxx_messageInfo_DoSumResponse.Size(m)
}
func (m *DoSumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoSumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoSumResponse proto.InternalMessageInfo

func (m *DoSumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumberRequest struct {
	PrimeNo              int64    `protobuf:"varint,1,opt,name=primeNo,proto3" json:"primeNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberRequest) Reset()         { *m = PrimeNumberRequest{} }
func (m *PrimeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberRequest) ProtoMessage()    {}
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{3}
}

func (m *PrimeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberRequest.Unmarshal(m, b)
}
func (m *PrimeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberRequest.Merge(m, src)
}
func (m *PrimeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberRequest.Size(m)
}
func (m *PrimeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberRequest proto.InternalMessageInfo

func (m *PrimeNumberRequest) GetPrimeNo() int64 {
	if m != nil {
		return m.PrimeNo
	}
	return 0
}

type PrimeNumberResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberResponse) Reset()         { *m = PrimeNumberResponse{} }
func (m *PrimeNumberResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberResponse) ProtoMessage()    {}
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{4}
}

func (m *PrimeNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberResponse.Unmarshal(m, b)
}
func (m *PrimeNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberResponse.Merge(m, src)
}
func (m *PrimeNumberResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberResponse.Size(m)
}
func (m *PrimeNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberResponse proto.InternalMessageInfo

func (m *PrimeNumberResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ComputeAverageRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageRequest) Reset()         { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()    {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{5}
}

func (m *ComputeAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageRequest.Unmarshal(m, b)
}
func (m *ComputeAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageRequest.Marshal(b, m, deterministic)
}
func (m *ComputeAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageRequest.Merge(m, src)
}
func (m *ComputeAverageRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageRequest.Size(m)
}
func (m *ComputeAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageRequest proto.InternalMessageInfo

func (m *ComputeAverageRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAverageResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageResponse) Reset()         { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()    {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271ad2b08a2bc1c2, []int{6}
}

func (m *ComputeAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageResponse.Unmarshal(m, b)
}
func (m *ComputeAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageResponse.Marshal(b, m, deterministic)
}
func (m *ComputeAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageResponse.Merge(m, src)
}
func (m *ComputeAverageResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageResponse.Size(m)
}
func (m *ComputeAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageResponse proto.InternalMessageInfo

func (m *ComputeAverageResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Sum)(nil), "sum.Sum")
	proto.RegisterType((*DoSumRequest)(nil), "sum.DoSumRequest")
	proto.RegisterType((*DoSumResponse)(nil), "sum.DoSumResponse")
	proto.RegisterType((*PrimeNumberRequest)(nil), "sum.PrimeNumberRequest")
	proto.RegisterType((*PrimeNumberResponse)(nil), "sum.PrimeNumberResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "sum.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "sum.ComputeAverageResponse")
}

func init() {
	proto.RegisterFile("calculator/sumpb/sum.proto", fileDescriptor_271ad2b08a2bc1c2)
}

var fileDescriptor_271ad2b08a2bc1c2 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xbe, 0x0d, 0xc5, 0x0c, 0x60, 0x74, 0x8c, 0x48, 0xd6, 0x8b, 0xae, 0x07, 0x89,
	0x89, 0x40, 0xf0, 0x13, 0xa0, 0x5c, 0x3c, 0x60, 0x4c, 0xb9, 0x79, 0x31, 0x50, 0x57, 0x43, 0xc2,
	0x76, 0xd7, 0xfd, 0xe3, 0x27, 0xf5, 0x03, 0x99, 0x4e, 0xbb, 0xa6, 0x48, 0x2f, 0x4d, 0xe6, 0x99,
	0xa7, 0xcf, 0x6f, 0x67, 0x32, 0xc0, 0xb2, 0xd5, 0x36, 0xf3, 0xdb, 0x95, 0x53, 0x66, 0x6c, 0xbd,
	0xd4, 0xeb, 0xe2, 0x3b, 0xd2, 0x46, 0x39, 0x85, 0xb1, 0xf5, 0x92, 0x2f, 0x20, 0x5e, 0x7a, 0x89,
	0x97, 0xd0, 0x7d, 0xdf, 0x18, 0xeb, 0x5e, 0x73, 0x2f, 0xd7, 0xc2, 0x0c, 0xa2, 0x8b, 0x68, 0xd8,
	0x4a, 0x3b, 0xa4, 0x3d, 0x91, 0x84, 0x57, 0xd0, 0xb3, 0x22, 0x53, 0xf9, 0x5b, 0xf0, 0xfc, 0x27,
	0x4f, 0xb7, 0x14, 0x4b, 0x13, 0xbf, 0x81, 0xee, 0x5c, 0x2d, 0xbd, 0x4c, 0xc5, 0xa7, 0x17, 0xd6,
	0x21, 0x83, 0x82, 0x42, 0x71, 0x9d, 0xe9, 0xc1, 0xa8, 0x80, 0x17, 0x5d, 0x42, 0x5f, 0x43, 0xaf,
	0xf2, 0x5a, 0xad, 0x72, 0x2b, 0xb0, 0x0f, 0x89, 0x11, 0xd6, 0x6f, 0x5d, 0x85, 0xaf, 0x2a, 0x3e,
	0x02, 0x7c, 0x36, 0x1b, 0x29, 0x4a, 0x46, 0x88, 0x1e, 0x40, 0x5b, 0x93, 0xaa, 0xc8, 0x1e, 0xa7,
	0xa1, 0xe4, 0xb7, 0x70, 0xb2, 0xe3, 0x6f, 0x8c, 0x8f, 0x7f, 0xe3, 0xc7, 0x70, 0xfa, 0xa0, 0xa4,
	0xf6, 0x4e, 0xcc, 0xbe, 0x84, 0x59, 0x7d, 0x88, 0x40, 0xe8, 0x43, 0x52, 0x5b, 0x47, 0x9c, 0x56,
	0x15, 0x9f, 0x40, 0xff, 0xef, 0x0f, 0x8d, 0x88, 0x28, 0x20, 0xa6, 0xdf, 0x11, 0x24, 0x4b, 0x2f,
	0x67, 0x7a, 0x83, 0x13, 0x68, 0xd1, 0xd4, 0x78, 0x4c, 0xdb, 0xa8, 0x6f, 0x8b, 0x61, 0x5d, 0x2a,
	0x23, 0xf9, 0x3f, 0x7c, 0x84, 0xa3, 0xda, 0x38, 0x73, 0x91, 0x29, 0x89, 0x67, 0xe4, 0xdc, 0xdf,
	0x0a, 0x1b, 0xec, 0x37, 0x42, 0xd0, 0x24, 0xc2, 0x05, 0x1c, 0xee, 0xbe, 0x1c, 0x19, 0xf9, 0x1b,
	0xe7, 0x67, 0xe7, 0x8d, 0xbd, 0x10, 0x37, 0x8c, 0xee, 0xdb, 0x2f, 0x2d, 0x3a, 0xaa, 0x75, 0x42,
	0x17, 0x75, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x83, 0x36, 0xc8, 0x1d, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumApiClient is the client API for SumApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumApiClient interface {
	// Unary
	DoSum(ctx context.Context, in *DoSumRequest, opts ...grpc.CallOption) (*DoSumResponse, error)
	// Streaming
	PrimeNumberDecom(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (SumApi_PrimeNumberDecomClient, error)
	//Client Streaming
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (SumApi_ComputeAverageClient, error)
}

type sumApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSumApiClient(cc grpc.ClientConnInterface) SumApiClient {
	return &sumApiClient{cc}
}

func (c *sumApiClient) DoSum(ctx context.Context, in *DoSumRequest, opts ...grpc.CallOption) (*DoSumResponse, error) {
	out := new(DoSumResponse)
	err := c.cc.Invoke(ctx, "/sum.SumApi/DoSum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sumApiClient) PrimeNumberDecom(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (SumApi_PrimeNumberDecomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SumApi_serviceDesc.Streams[0], "/sum.SumApi/PrimeNumberDecom", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumApiPrimeNumberDecomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SumApi_PrimeNumberDecomClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type sumApiPrimeNumberDecomClient struct {
	grpc.ClientStream
}

func (x *sumApiPrimeNumberDecomClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sumApiClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (SumApi_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SumApi_serviceDesc.Streams[1], "/sum.SumApi/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumApiComputeAverageClient{stream}
	return x, nil
}

type SumApi_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type sumApiComputeAverageClient struct {
	grpc.ClientStream
}

func (x *sumApiComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sumApiComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SumApiServer is the server API for SumApi service.
type SumApiServer interface {
	// Unary
	DoSum(context.Context, *DoSumRequest) (*DoSumResponse, error)
	// Streaming
	PrimeNumberDecom(*PrimeNumberRequest, SumApi_PrimeNumberDecomServer) error
	//Client Streaming
	ComputeAverage(SumApi_ComputeAverageServer) error
}

// UnimplementedSumApiServer can be embedded to have forward compatible implementations.
type UnimplementedSumApiServer struct {
}

func (*UnimplementedSumApiServer) DoSum(ctx context.Context, req *DoSumRequest) (*DoSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSum not implemented")
}
func (*UnimplementedSumApiServer) PrimeNumberDecom(req *PrimeNumberRequest, srv SumApi_PrimeNumberDecomServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecom not implemented")
}
func (*UnimplementedSumApiServer) ComputeAverage(srv SumApi_ComputeAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}

func RegisterSumApiServer(s *grpc.Server, srv SumApiServer) {
	s.RegisterService(&_SumApi_serviceDesc, srv)
}

func _SumApi_DoSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumApiServer).DoSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.SumApi/DoSum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumApiServer).DoSum(ctx, req.(*DoSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SumApi_PrimeNumberDecom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SumApiServer).PrimeNumberDecom(m, &sumApiPrimeNumberDecomServer{stream})
}

type SumApi_PrimeNumberDecomServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type sumApiPrimeNumberDecomServer struct {
	grpc.ServerStream
}

func (x *sumApiPrimeNumberDecomServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SumApi_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SumApiServer).ComputeAverage(&sumApiComputeAverageServer{stream})
}

type SumApi_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type sumApiComputeAverageServer struct {
	grpc.ServerStream
}

func (x *sumApiComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sumApiComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SumApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sum.SumApi",
	HandlerType: (*SumApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSum",
			Handler:    _SumApi_DoSum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecom",
			Handler:       _SumApi_PrimeNumberDecom_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _SumApi_ComputeAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/sumpb/sum.proto",
}
